alias nv3='. ~/neovim3/bin/activate'
alias nv2='. ~/neovim2/bin/activate'
alias csi='. ~/csi/bin/activate'
alias esperf='. ~/esperf/bin/activate'
alias saltp='. ~/salt/bin/activate'
alias infraapi='. ~/cps-infra-api/bin/activate'
alias tbd='. ~/tbd/bin/activate'
alias realt='. ~/realt/bin/activate'
alias pyvcms='. ~/vcms/bin/activate'
alias mux="tmuxinator"
alias glg="git log --graph --decorate --all"
