#!/usr/bin/env sh

# Terminate running polybar
# Wait for it to be killed.
while pgrep -u $UID -x polybar >/dev/null; do
  killall -q polybar
  sleep 1
done

# Launch bar
polybar primary &
polybar secondary &
# Uncomment if a third monitor is connected
polybar third &
